### ISSUE TITLE
Chinese semester start/end date

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#10]
Using the following assumption,

1st semester, September 1st - January 31st year+1
2nd semester, February 1st - 31th August

**Comment by mylaluna** [comment]
Let me confirm with it.

**Comment by mylaluna** [comment]
according to the client, junior and senior students have slightly different schedule. 
For example, junior's semester always end one week before senior's. I guess we should not worry about this.

In general, semester begins from 1st March or 1st September, fixed.

**Comment by keke8273** [comment]
Cool. I am content with school years, such as 2014-2015学年度, for the time being.
