### ISSUE TITLE
Lack of Arts Class QS Detail Report

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#108]
If users update any existing exam for arts and then select exporting reports, they will not be able to find Class QS Detail Report for each class.

**Comment by keke8273** [comment]
App deleted exam info even though user cancels the update request.

**Comment by keke8273** [comment]
Fixed in #114 . Await Verification

**Comment by mylaluna** [comment]
Problems:
Cannot output previously uploaded exams' reports, particularly the sciences side.
Similar to the issue above, just 4 reports were generated, and they are all empty.

(Verified in version 1.0.0.15_Win10)

**Comment by keke8273** [comment]
#136

**Comment by mylaluna** [comment]
Cannot import exams correctly.

(Verified in version 1.0.0.15_Win10)

**Comment by keke8273** [comment]
unrelated issue.

**Comment by mylaluna** [comment]
All reports are generated correctly.
