### ISSUE TITLE
Desktop App crashed at key validation Page

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#109]
Happened on VM machine, desktop app crashed when confirming about the authentication key,
Users need to relaunch the app to very to bypass the authentication screen.

**Comment by keke8273** [comment]
More information required. Uninstall the app on your Vm. Install again, try to active the app with the same key. See if the app crash again.

**Comment by mylaluna** [comment]
Reinstall requires a new key. It was saying the key has been used.

**Comment by keke8273** [comment]
So it didnt crash this time? 

And yes, one license can only be activated once. Currently, user uninstalls the app will leave the license activated, refer to #96 . Ideally, the user should be need to uninstall the app, they will do updates from time to time, which will migrate their registration info between versions.

**Comment by mylaluna** [comment]
I could not run the app because the key is not valid anymore. Give me a new key.

**Comment by keke8273** [comment]
I will manually deactivate your VM key.

**Comment by mylaluna** [comment]
It looks good now.
