### ISSUE TITLE
App enters a dead state when user uploads xls files

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#111]
App support xlsx files only

**Comment by keke8273** [comment]
The app does allow xls input, which can be taken out easily. 

However, give that the client may a lot of historical xls (Excel 2003) file, we will keep allowing the input and convert it to [xlsx (Excel 2007) programmably](http://stackoverflow.com/questions/18904561/programmatically-convert-excel-2003-files-to-2007) then process it .

**Comment by keke8273** [comment]
Dispose EEPackage after use.

**Comment by keke8273** [comment]
Fixed in #113. Await Verification.

**Comment by keke8273** [comment]
The solution i put in yesterday relies on a specific version of Excel is installed on the target computer, which is not good. Looking [into this OLEDB](http://www.codeproject.com/Tips/705470/Read-and-Write-Excel-Documents-Using-OLEDB) solution today

**Comment by keke8273** [comment]
#119 Disallow xls input as discussed. 

Need Verification

**Comment by mylaluna** [comment]
Fixed. Users now cannot only select xlsx files to upload. 
(Verified in version 1.0.0.15_Win10)
