### ISSUE TITLE
App crash when transit from NewClass to SchoolManagement

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#121]
When the extra information boxes such as grades and "可多选" is displayed, transit away from the view causes app crash.

**Comment by mylaluna** [comment]
Verify when 可多选 of add exam blade is displayed and click on 学校管理 will not crashed the app.
However, switch back to the add exam blade makes 可多选 disappear.
If this is expected, closed this issues.

(Verified in version 1.0.0.15_Win10)

**Comment by keke8273** [comment]
expected. Close 添加考试 to redisplay it.
