### ISSUE TITLE
Update teacher assignment seeding 

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#122]

**Comment by keke8273** [comment]
Added new teacher assignment information for 2015-2016 year.

**Comment by mylaluna** [comment]
Two issues here:

- I give you two batches teacher assignments but I cannot verify if the early one is correctly imported. Some of the assignments may have been overridden by the later assignment. Maybe we need to have a view of historical teacher assignment for this class? 
- Have arts classes had biology subject before? If they had biology before,  and now they discontinue the subject, we should not be able to change or display biology for the arts classes. So are the science classes.

**Comment by keke8273** [comment]
As discuss, they are not affecting the results. So we will leave it as is for the time being. 

As for assignment history, it is a nice to have, I will leave this issue open to track that requirement.

**Comment by keke8273** [comment]
raised #144, close this one.
