### ISSUE TITLE
App crash when reporting if a report is opened by another process

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#123]
Should report error instead.

**Comment by keke8273** [comment]
App reports error instead of crashing if an existing report is opened by a user while it is trying to overwrite  it.

**Comment by mylaluna** [comment]
Verify the error message. What is happening now is the app will generate report files one by one and stop at the file it cannot modify. This will result in half of the file list gets updated but another half will stay at the old version. 

In the ideal situation, I believe we should either abandon the entire file update process if any file goes wrong or we should just skip the problem file and continue update other files.

**Comment by keke8273** [comment]
To abandon the generated report and go back the previous version is not a trivial task. We can discuss if that strategy is required. This issue is just to track the bug. If the bug is fixed, we should close it. Raise new issue if required.

**Comment by mylaluna** [comment]
Is it easy to skip the problem file and generate a simple error report in an error folder, which tells users which files are not populated correctly?

**Comment by keke8273** [comment]
The app currently dont not allow generating a single report. If a report is need, the user must generates all reports. When the reporting service go wrong, what the user will do is regenerating all the reports again, which will overwrite all the existing reports. Therefore, I dont think we need to do this yet.

**Comment by mylaluna** [comment]
If users do not pay attention to the quickly disappeared warning message, how do they know they should "regenerate everything".

**Comment by keke8273** [comment]
App no longer crash if a report is opened. The other feature discussed here will be considered in later releases.
