### ISSUE TITLE
Parse file name to prefill new exam view fields

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#124]
This require the user to provide test result files in a specified format. 

The app will attempt to parse the file and prefill some of the views.

If the parse failed, the user is still able to update any of the field manually.

**Comment by keke8273** [comment]
use the file format from the first client as the standard

2014-2015学年度第二学期高一期末考试成绩表

**Comment by keke8273** [comment]
Need verification

**Comment by keke8273** [comment]
Moved the button to the header. so it make user choose file first naturally.

**Comment by mylaluna** [comment]
This is cool.
(Verified in version 1.0.0.18_Win10)
