### ISSUE TITLE
Update Teacher Progress Rate Algorithm.

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#134]
Previous, if a teacher has no assignment in the last exam, no progress rate is calculated.  Should recalculate the teacher pr using current teacher assignment.

**Comment by mylaluna** [comment]
Tested with:
2015-2016第二学期_期中考试_文科_20160329;
2015-2016第二学期_期末考试_文科_20160630;

Teacher 李志强's PR is 3.

Pass.
(Verified in version 1.0.0.17_Win10)
