### ISSUE TITLE
Cannot update exams correctly

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#135]
- Update an uploaded exam, for both arts and science parts, with the same exam file will only update either arts or science part.  This is picked up by looking at the "last update time" column.
- Update an exam with a different exam date will be ignored by our app.

(Found in version 1.0.0.15_Win10)

**Comment by keke8273** [comment]
Can not replicate issue 1. At my end, if I confirm on both exams, both exams are updated. Did you confirm twice? 

Issue 2, exam update is not ignored. Instead the exam date is not update when updating an exam. I guess I will allow exam date to be updated too. 

For future reference raise two separate issues.

**Comment by mylaluna** [comment]
Delete database and retest this issue. 
The issue now is user cannot import science exam.

**Comment by mylaluna** [comment]
The problem is due to the exam file contains illegal content.
Separated issues #150 raised.
