### ISSUE TITLE
Update all progress rate algorithm

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#146]
Eliminate students who only participated in one exam out of the PR calculation.

**Comment by keke8273** [comment]
Steps to calculate teacher progress rate:
1. Identify current exam Id,
2. Identify previous exam Id. if no previous exam is found. return NaN.
3. Found all valid student in the current exam.
4. Found all valid student in the previous exam.
5. Calculate the join of these two student groups.
6. Identify teacher assignment for current exam.
7. Identify teacher assignment for the previous exam. if the assignment is different, use the current assignment.
8. Recalculate current QS1 with current assignment and student scores
9. Recalculate previous QS1 with current assignment and student scores.
10. Calculate the progress rate.

**Comment by mylaluna** [comment]
The steps above are correct.

**Comment by mylaluna** [comment]
Tried to test calculation result by hand. Following steps are obtained for calculating PR between:
2015-2016第二学期_期中考试_文科_20160329;
2015-2016第二学期_期末考试_文科_20160630;

Particularly, for arts direction, class 2, English teacher 李欢欢.

Class 2's English Stanine for 2015-2016第二学期_期中考试_文科_20160329 is as following:
0, 0, 9, 11, 13, 9, 7, 1, 0 (total 50)

Class 2's English Stanine for 2015-2016第二学期_期末考试_文科_20160630 is like below:
0, 2, 3, 17, 7, 10, 6, 1, 4 (total 50)

The difference the above two are:
0, 2, -6, 6, -6, 1, -1, 0 ,4

times Stanine scales:
0 + 16 -42 + 36 -30 +4 - 3 +0 +4

Result is -15

**Comment by mylaluna** [comment]
Manually Calculated correctly.
(Verified in version 1.0.0.17_Win10)
