### ISSUE TITLE
Normalize QS1 to 100

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#147]

**Comment by keke8273** [comment]
[Simple Normalization Strategies](http://stats.stackexchange.com/questions/70801/how-to-normalize-data-to-0-1-range
)

**Comment by mylaluna** [comment]
Secretly pass.
(Verified in version 1.0.0.17_Win10)

**Comment by mylaluna** [comment]
This normalization made reproducing result manually become extremely difficult for teachers.
