### ISSUE TITLE
Need warning message when importing an irregular format exam file

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#150]
## Instruction:
The exam files sent to us currently are not regulated in a fixed format. 
It is very common that these exam files contain content that our app cannot handle.

At the moment, the app will just stop reading when something goes wrong and display "successfully import 0 exams".

## Requirement:
- Show a warning message when above case encountered.
- The warning message can include more information such as "report analysis stopped at line 246" or something similar. This will help users to locate illegal content and thereby correct it.

**Comment by keke8273** [comment]
![image](https://cloud.githubusercontent.com/assets/12285111/18435870/ed1fa3ba-7938-11e6-9ccf-152d2781ab67.png)

**Comment by mylaluna** [comment]
pass. 
(Verified in version 1.0.0.17_Win10)
