### ISSUE TITLE
Add an exam detail view

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#152]
show exam statistics.
allow use to compare selected exam to another exam with the same study direction attribute. 
we dont allow science test result comparing with art test results

**Comment by keke8273** [comment]
need verification

**Comment by mylaluna** [comment]
New exam detail view displays correct result that matches generated report.
However, the generated report has been affected that display records in  messed up order.

**Comment by keke8273** [comment]
Need verification

**Comment by mylaluna** [comment]
Verified in 1.1.0.3
