### ISSUE TITLE
Update report header to save some space

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#155]
- 教师量化

“教师姓名” -> "教师"
“任教科目” -> "科目"
"实际参考人数" -> “参考人数”
”有效参考人数“ -> ”有效人数“ 
”九分段人数“ -> "九分段"
”八分段人数“ -> "八分段"
”七分段人数“ -> "七分段"
”六分段人数“ -> "六分段"
”五分段人数“ -> "五分段"
”四分段人数“ -> "四分段"
”三分段人数“ -> "三分段"
”二分段人数“ -> "二分段"
”一分段人数“ -> "一分段"

**Comment by mylaluna** [comment]
Renamed.
(Verified in version 1.0.0.17_Win10)
