### ISSUE TITLE
Allow user to change class studydirection attribute.

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#168]
After a class changes its studydirection, a new class entity will be created. And the previous one is marked as inactive. 

The new class will inherit all teacher assignments from the old class. User can update teacher assignment as normal.

User cant compare exam results of these two class entities.

**Comment by keke8273** [comment]
Need verification.

**Comment by mylaluna** [comment]
Verify the new fancy feature and it is working.
However, there is a small bug:
When users are saving study direction change, the app will automatically highlight the class list and report there is unsaved changes. This may due to the incorrect way of fixing a previous highlight bug. ;)

**Comment by mylaluna** [comment]
Additional question, how does the app pre-select teachers when users changed study direction.

**Comment by keke8273** [comment]
Need verification

**Comment by mylaluna** [comment]
Fixed.
(Verified in version 1.0.0.19_Win10)
