### ISSUE TITLE
Implicit Stanine Scale Number Config

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#169]
## Instruction
Users can config how many Stanine Scales are needed in the report. This configuration would affect both calculation and display of the QS reports. 

## Issues
At the moment, this configuration sits at the top right corner of the app and users need to re-analyse/import target exam file to make the configuration work. However, there is no direct hint for users to do so. 

Additionally, reports always show 9 scales to users regardless the configuration. This is an inconsistent with the calculation as well.

## Requirements
Choose one of following:
- Add a hint words next to the Stanine Scales configuration: （更改此设置需要重新导入考试文件）
- Move the configuration to Add New Exam blade.
- Make regenerate report being aware of changing on Stanine Scales configuration.

(Optional) Change reports display to be consistent with Stanine Scales configuration.

**Comment by keke8273** [comment]
Change the implementation, that the number of scale is applied on report generation instead of exam analysis. So the user can change the user settings to generate different reports, instead of re-analyze the same exam time and time again.

**Comment by mylaluna** [comment]
Updated scale number configuration is now directly reflected in regenerated reports.

Remember there is a reason behind the original design. It is for the web calculation.
(Verified in version 1.0.0.18_Win10)

**Comment by keke8273** [comment]
What is the original design?
