### ISSUE TITLE
Unable to reopen Class Details View

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#170]
## Menu Path
Pikeman > School Management > Class Management > Class Details View

## Reproduce Steps
1. Click on any class will open the Class Details View. 
2. Close the Class Details View.
3. Click on the same class again will not reopen any class detail view.

**Comment by keke8273** [comment]
Need verification

**Comment by mylaluna** [comment]
Fixed.
(Verified in version 1.0.0.18_Win10)
