### ISSUE TITLE
Identify unused scales in the report.

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#171]
if less than 9 scales are used in the exam analysis, identify the unused scales in the report

**Comment by keke8273** [comment]
![image](https://cloud.githubusercontent.com/assets/12285111/18630743/c3137960-7eb1-11e6-8812-a2cb4bf8d8dd.png)
 unused scales are marked with "未计入". User can deduce how many scales are used in the QS calculation

**Comment by keke8273** [comment]
Need verification

**Comment by mylaluna** [comment]
Add * in front of scale title indicating excluded from calculation.
(Verified in version 1.0.0.18_Win10)
