### ISSUE TITLE
Update report header

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#177]
班级量化明细：
分段人数（2）-> 7分段人数（2）
段位位线 -> 段位最低分数线

教师量化:
九分段  -> 九分段人数

班级量化:
九分段  -> 九分段人数

量化段位分数线：

九分段段位线 -> 九分段最低分数线

**Comment by keke8273** [comment]
Need verification

**Comment by mylaluna** [comment]
Rename request is from client. Done.
(Verified in version 1.0.0.18_Win10)
