### ISSUE TITLE
Scale Teacher Qs2 by 10 instead of 100

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#179]

**Comment by keke8273** [comment]
Bug caused by client. Need verification

**Comment by mylaluna** [comment]
what was the bug?

**Comment by keke8273** [comment]
QS2 was scaled by 100 as requested by the client. Then he requested to reduce the factor by 10.

**Comment by mylaluna** [comment]
pass
(Verified in version 1.0.0.18_Win10)
