### ISSUE TITLE
App crashes when process a file without required worksheet

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#191]
Load 2015-2016学点度第一学期高一期中考试成绩表 and ask for “文科”or "理科". App crashes because the file doesnot contain such worksheet

**Comment by keke8273** [comment]
App report error gracefully.

![image](https://cloud.githubusercontent.com/assets/12285111/18708352/c323a3c0-803d-11e6-88cd-bdc0a59f6524.png)

**Comment by mylaluna** [comment]
(Verified in version 1.0.0.19_Win10)
