### ISSUE TITLE
Hard to repick a study direction when Import an exam

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#198]
## Instruction
Delete a study direction and add back a study direction can be annoying for users when importing an exam.

## To Reproduce
- Go to add exam blade;
- pick a study direction;
- delete the study direction;
- pick a study direction again;
- users will find nothing really show up in the text box.

**Comment by keke8273** [comment]
Need verification

**Comment by mylaluna** [comment]
Fixed
(Verified in version 1.0.0.20_Win10)
