### ISSUE TITLE
Added a new type of class QS detail report

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#206]
add 班级量化明细_综合
rename current 班级量化明细 to 班级量化明细_单科

**Comment by keke8273** [comment]
![image](https://cloud.githubusercontent.com/assets/12285111/18829177/790c336c-841e-11e6-99f3-30cbae44bff8.png)

**Comment by mylaluna** [comment]
Unable to see the change.

**Comment by mylaluna** [comment]
Confirm changes.
(Verified in version 1.0.0.22_Win10)
