### ISSUE TITLE
Setup an email service on azure

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#212]
https://azure.microsoft.com/en-us/documentation/articles/sendgrid-dotnet-how-to-send-email/

**Comment by keke8273** [comment]
setup an email service on azure to switch from third-party email service provider. Hopefully, we will not lose any user feedback anymore.

**Comment by mylaluna** [comment]
Sending a feedback Email. Please verify receive.

**Comment by keke8273** [comment]
feedback recieved.

**Comment by mylaluna** [comment]
Pass version 1.1.0.1
