### ISSUE TITLE
Progress Rate between any two exams

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#213]
## Background
At the moment, the progress rate can only be generated between exams that are next to each other.

## Requirement
Add a function to generate progress rate between any two comparable exams.

**Comment by mylaluna** [comment]
The progress rate between any two exams does not need to be displayed in the report?
Progress rate includes class PR and teacher PR.
This should be a display of teacher management.

**Comment by keke8273** [comment]
Exam with the same study direction can be compared. 
Exam can only compare to exams that were taken before. Not after. For example, 1,2,3 exams happened in sequence. Exam 1 has no comparable exams. Exam 2 can compare to Exam 1. Exam 3 can compare to both Exam 1 and 2.

**Comment by mylaluna** [comment]
Correct implementation verified in 1.1.0.1
