### ISSUE TITLE
Class management detail update bug

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#227]
# Instruction
There is a bug in the Class Management View.
When users try to change study direction and teacher assignment at the same time.
Clicking on 'update' button will result:
- App prompts confirmation message about if user want to give up the change.
- App lost focus on current class

# Requirement
- Change class detail update process
- App never lose focus on processing class

**Comment by keke8273** [comment]
Fixed the bug where unsave data popup is display unintentionlly.

**Comment by mylaluna** [comment]
fixed in 1.1.04
