### ISSUE TITLE
Results doubled in exam detail view

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#237]
# Introduction
We have spotted that in a certain situation that all results in exam detail view get show twice.

# Steps to reproduce
- click one exam, wait for it to finish calculation
- click one another exam, while it is calculating, switch to the one that is just calculated.
- then immediately switch back to the one that is calculating

**Comment by keke8273** [comment]
fixed. need verification

**Comment by mylaluna** [comment]
Fixed in 1.1.05
