### ISSUE TITLE
Duplicated subject teacher assignment tiles in Class Detail view

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#239]
# Introduction
This one comes from our client. Somehow he was ended up with assigning four bio teachers for one class.
This is clearly wrong.

# Requirement
Fix the bug and we should design the process better so that this thing will never appear.

**Comment by keke8273** [comment]
# Repo Step

1. Go into ClassDetail View.
2. Change any subject's teacher assignment
3. Click update button.
4. Close App and Relaunch App
5. Go into ClassDetail View of the same class.
6. Found duplicated subject tiles.

**Comment by mylaluna** [comment]
Fixed in 1.1.0.5
