### ISSUE TITLE
Autofill monthly exam file to Import Exam View

### ISSUE THREAD

**Issue by mylaluna** [keke8273/Pikeman#240]
# Introduction
Due to previously lack of data, monthly exam file parser is not concerned.

# Requirement
Add parser for monthly exams.

**Comment by keke8273** [comment]
use 2016-2017学年度第一学期高三月考第二次成绩表
instead of 2016-2017学年度第一学期高三第二次月考成绩表

**Comment by keke8273** [comment]
at this moment, this is no clear standard way to name a exam result file. Any implementation would be useless if the file name changes. For time being, using the workaround suggested above or select the exam type manually in app.

**Comment by mylaluna** [comment]
Confirm parser working on 2016-2017学年度第一学期高三月考第二次成绩表.
Although, 月考第二次 feels unnature comparing with 第二次月考

**Comment by keke8273** [comment]
understand that. we need make an agreement with the school before updating our implementation
