### ISSUE TITLE
Typing non-numeric string in the new class view does not yield correct validation message

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#250]
Expected error message
![image](https://cloud.githubusercontent.com/assets/12285111/19750712/3db0b138-9c3f-11e6-8d2c-8dd25756a035.png)

Actual error message

![image](https://cloud.githubusercontent.com/assets/12285111/19750716/4be3df6e-9c3f-11e6-9ecb-989146e9d6a2.png)

**Comment by mylaluna** [comment]
Fixed in 1.2.0.2
