### ISSUE TITLE
App crashes when updating teacher detail

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#264]
App crashed sometime when updating teacher detail
# Repo Step
1. Go to Teacher Management view
2. Select a Teacher
3. Click Class Management to switch to Class Management view
4. Click Teacher Management to switch to Teacher Management view again.
5. Select any teacher
6. Change the teacher's personal information. 
7. Click Update button, app crashes.

**Comment by mylaluna** [comment]
Fixed in 1.2.0.6
