### ISSUE TITLE
Teacher assignment linked to semester

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#5]
During the implementation, it is realized that teacher assignment is not necessarily tight to a specific semester. Teacher assignment can change during a semester due to personal issue. Teach assignment can stay the same between two or more semesters. 

Therefore, it is more reasonable to record the date when the teach assignment is update. To look up a teacher assignment, get the exam date and search backward to the last known teach assignment. This creates more work but it is the correct implementation.

**Comment by mylaluna** [comment]
Reasonable, any change to database tables? what are the columns for teacherassignment table?

**Comment by mylaluna** [comment]
Can your parser understand '2014 高一 第二学期' and translate it into relevant period for teacherassignment record?

**Comment by mylaluna** [comment]
The benefits of using Semester or TeacherAssignDate are both valid. 
If we use Semester, I feel we can get business logic facilitated to find a valid period for calculating QS.
If we use TeacherAssignDate, I feel we are going to have accurate Teacher Assigning Period and it can be used for other purpose.

**Comment by keke8273** [comment]
No the parse can't translate exam name into dates. But the meta data we collect before uploading the result does have the exam date

**Comment by keke8273** [comment]
Currently the TA is made of semesterId, subjectId, teacherId, and classId

**Comment by keke8273** [comment]
It seems that TeacherAssignment need to be linked to a semester. We could add an AssignmentDate but Semester is required for sure. When TeacherAssignment is used, we normally starts with an exam, which is linked to a Semester naturally. We often want to ask what is the TeacherAssignment for this exam. Answering this question via the Semester link is relatively easy. However, query by the AssignmentDate and ExamDate is very complicated if not impossible. For the time being we will keep it simple and keep linking a TeacherAssignment to a Semester.

**Comment by keke8273** [comment]
removed the semester -> teacher assignment link. 
teacher assignment is purely searched by DateAssigned property.

#74
