### ISSUE TITLE
App failed to navigate away from the new class view when click the class that was selected before in the class management view

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#69]
Replicate steps:
1. Select a class in the class list view.
2. Click new class button to show new class view.
3. Select the SAME class in the class list view.
4. App failed to navigate back into the class detail view.

**Comment by keke8273** [comment]
Wait for verification

**Comment by mylaluna** [comment]
Fix verified in version 1.0.0.16_Win10
