### ISSUE TITLE
Reselect the previous item when navigation request is canceled.

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#72]
The selected an item in the class listview.
Move to the class detail view and make some updates. Do Not save your changes. 
Click on another class in the class listview.
Cancel the Navigation
Even though the user cancels the navigation, the selected item in the listview is changed.

**Comment by keke8273** [comment]
Needs verification

**Comment by mylaluna** [comment]
Fixed.
(Verified in version 1.0.0.17_Win10)
