### ISSUE TITLE
What to do when the same exam updated more than once

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#8]

**Comment by mylaluna** [comment]
I think we have discussed this question in the early design stage.
All I remember now is we cannot delete everything that we have added.

I was wondering if we could do following:

1. Add server side and front end validation that warn the user there are existing similar exam
2. Add a flag field to the Exam table, for example, "active", whenever a similar exam is added, we can turn this flag to "Inactive"
3. At the front end, we only display the 'Active' exam.

Alternatively, we can write sql query that only display us the latest version for each exam. Remember user can only do operations on the exam they can see.

The key point here is how we identify similar exams.

I feel we can use your idea: the meta data in add exam interface to tell the difference. 

what do you think?

**Comment by keke8273** [comment]
#94
