### ISSUE TITLE
Show something else when the listview is empty

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#93]
a empty listview does not look pretty.

**Comment by keke8273** [comment]
![image](https://cloud.githubusercontent.com/assets/12285111/18436530/3185b410-793c-11e6-88b1-393711e84478.png)

**Comment by mylaluna** [comment]
Tested, working, it would be better if click on add exam can make empty list disappear but I will pass this.
(Verified in version 1.0.0.17_Win10)
